apiVersion: v1
kind: Service
metadata:
  name: fullnode-polkadot
spec:
  selector:
    app: fullnode-polkadot
  ports:
    - protocol: TCP
      port: 9944
      targetPort: 9944
      name: ws
    - protocol: TCP
      port: 9933
      targetPort: 9933
      name: http
