apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fullnode-polkadot
spec:
  serviceName: "fullnode-polkadot"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: fullnode-polkadot
  template:
    metadata:
      labels:
        app: fullnode-polkadot
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: parity
        image: parity/polkadot:v0.9.12
        command: ["polkadot"]
        args: ["--chain", "polkadot", "-d", "/data", "--rpc-external", "--ws-external"]
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 9944
          name: ws
        - containerPort: 9933
          name: http
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
          tcpSocket:
            port: http
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
          tcpSocket:
            port: http
        startupProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
          tcpSocket:
            port: http
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
